CREATE TABLE BOARD(
BNO NUMBER(10) PRIMARY KEY,
NAME VARCHAR2(20) NOT NULL,
PASSWORD NUMBER(20) NOT NULL,
TITLE VARCHAR2(20) NOT NULL,
CONTENT VARCHAR2(20) NOT NULL,
READACT NUMBER(20) DEFAULT 0,
REGDATE DATE DEFAULT SYSDATE
);
-- 시퀀스 생성 : 1씩 증가 BOARD_SEQ
CREATE SEQUENCE BOARD_SEQ; 